apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cybjax17g-nodejs 
  janus-idp.io/tekton: cybjax17g-nodejs
  backstage.io/kubernetes-id: cybjax17g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cybjax17g-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  